spring:
  application:
    name: product
 # jackson:
  #  property-naming-strategy: SNAKE_CASE

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
